; ORIGINAL DATA
g_serf_down1:   
                db  &12
                db  &1f, &38
                db  &17, &38
                db  &0e, &3c
                db  1, &5e
                db  3, &de
                db  &27, &ee
                db  &77, &70
                db  &77, &f4
                db  &77, &74
                db  &45, &d0
                db  0, &80
                db  &0a, &28
                db  &1b, &6c
                db  8, &0c
                db  &1c, &14
                db  &17, &fc
                db  &0d, &e8
                db  7, &50
g_serf_down2:   db  &12
                db  &0f, &f8
                db  &0d, &68
                db  6, &30
                db  1, &40
                db  &23, &e2
                db  &37, &f6
                db  &37, &76
                db  &17, &f4
                db  &17, &74
                db  5, &d0
                db  0, &80
                db  &0a, &28
                db  &1b, &6c
                db  8, &0c
                db  &1c, &14
                db  &17, &fc
                db  &0d, &e8
                db  7, &50
g_serf_down3:   db  &12
                db  7, &7c
                db  7, &74
                db  &1f, &58
                db  &3d, &60
                db  &3d, &e0
                db  &3b, &f2
                db  7, &77
                db  &17, &f7
                db  &17, &77
                db  5, &d2
                db  0, &80
                db  &0a, &28
                db  &1b, &6c
                db  8, &0c
                db  &1c, &14
                db  &17, &fc
                db  &0d, &e8
                db  7, &a0
g_serf_up1:     db  &12 
                db  &1e, &40
                db  &1e, &70
                db  &0a, &b0
                db  7, &d8
                db  &0f, &d8
                db  &4f, &e8
                db  &ef, &e0
                db  &ec, &6c
                db  &e2, &4c
                db  &8d, &a8
                db  &15, &70
                db  &1b, &d0
                db  &3a, &98
                db  &2b, &68
                db  &15, &d0
                db  &2f, &b8
                db  &13, &50
                db  &0a, &a0
g_serf_up2:     db  &12
                db  &0e, &e0
                db  &0e, &e0
                db  2, &80
                db  7, &c0
                db  &47, &c4
                db  &6f, &ec
                db  &6f, &ec
                db  &2c, &68
                db  &23, &88
                db  &0d, &a0
                db  &15, &70
                db  &1b, &d0
                db  &3a, &98
                db  &2b, &68
                db  &15, &d0
                db  &2f, &b8
                db  &13, &50
                db  &0a, &a0
g_serf_up3:     db  &12
                db  4, &f0
                db  &1c, &f0
                db  &1a, &a0
                db  &37, &c0
                db  &37, &e0
                db  &2f, &e4
                db  &0f, &ee
                db  &6c, &3e
                db  &63, &8e
                db  &2d, &a2
                db  &15, &70
                db  &1b, &d0
                db  &3a, &98
                db  &2b, &68
                db  &15, &d0
                db  &2f, &b8
                db  &13, &50
                db  &0a, &a0
g_serf_left1:   db  &12
                db  3, &70
                db  &0f, &78
                db  &3f, &1c
                db  &fb, &ec
                db  &cb, &10
                db  &77, &88
                db  7, &c8
                db  &37, &88
                db  &77, &30
                db  &0f, &c0
                db  &11, &50
                db  &60, &b8
                db  &68, &68
                db  &19, &d0
                db  7, &a8
                db  &19, &58
                db  &16, &f0
                db  &0a, &a0
g_serf_left2:   db  &12
                db  &3f, &e0
                db  &2f, &e0
                db  &24, &c0
                db  &19, &e0
                db  3, &f0
                db  6, &38
                db  6, &18
                db  7, &18
                db  7, &30
                db  &0f, &c0
                db  &11, &50
                db  &60, &b8
                db  &68, &68
                db  &19, &d0
                db  7, &a8
                db  &19, &58
                db  &16, &f0
                db  &0a, &a0
g_serf_left3:   db  &12
                db  3, &f0
                db  &3a, &f8
                db  &5a, &5c
                db  &4d, &9c
                db  &30, &30
                db  7, &f8
                db  8, &7a
                db  &18, &1a
                db  7, &3c
                db  &0f, &c0
                db  &11, &50
                db  &60, &b8
                db  &68, &68
                db  &19, &d0
                db  7, &a8
                db  &19, &58
                db  &16, &f0
                db  &0a, &a0
g_serf_right1:  db  &12
                db  &0f, &c0
                db  &1f, &5c
                db  &3a, &5a
                db  &39, &b2
                db  &0c, &0c
                db  &1f, &e0
                db  &5e, &10
                db  &58, &18
                db  &3c, &e0
                db  3, &f0
                db  5, &88
                db  &1d, 6
                db  &16, &16
                db  &0b, &98
                db  &15, &e0
                db  &1a, &98
                db  &0f, &e8
                db  5, &50
g_serf_right2:  db  &12
                db  7, &fc
                db  7, &f4
                db  3, &24
                db  7, &98
                db  &0f, &c0
                db  &1c, &60
                db  &18, &60
                db  &18, &e0
                db  &0c, &e0
                db  3, &f0
                db  5, &88
                db  &1d, 6
                db  &16, &16
                db  &0b, &98
                db  &15, &e0
                db  &1a, &98
                db  &0f, &e8
                db  5, &50
g_serf_right3:  db  &12
                db  &0e, &c0
                db  &1e, &f0
                db  &31, &fc
                db  &37, &df
                db  8, &d3
                db  &11, &ee
                db  &13, &e0
                db  &11, &ec
                db  &0c, &ee
                db  3, &f0
                db  5, &88
                db  &1d, 6
                db  &16, &16
                db  &0b, &98
                db  &15, &e0
                db  &1a, &98
                db  &0f, &e8
                db  5, &50